/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Client.java
 *
 * Created on 11 juin 2013, 08:53:44
 */
package view;

import controller.Controller;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.IOException;
import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author Quentin
 */
public class Client extends javax.swing.JFrame implements Observer, WindowListener {
	private Controller _contr;
	/** Creates new form Client */
	public Client() {
		initComponents();
		this.setVisible(true);
		this._contr = new Controller();
                jEditorPane1.setContentType("text/html");
	}
	
	public void write(String text){
            jEditorPane1.setText(text);
            area_content.setText(text);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_valider = new javax.swing.JButton();
        txt_port = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        area_content = new javax.swing.JTextArea();
        lbl_port = new javax.swing.JLabel();
        txt_adresse = new javax.swing.JTextField();
        lbl_adresse = new javax.swing.JLabel();
        editor = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_valider.setText("Envoyer");
        btn_valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_validerActionPerformed(evt);
            }
        });

        txt_port.setText("80");
        txt_port.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_portActionPerformed(evt);
            }
        });

        area_content.setColumns(20);
        area_content.setRows(5);
        jScrollPane1.setViewportView(area_content);

        lbl_port.setText("Port :");

        txt_adresse.setText("www.perdu.com");
        txt_adresse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_adresseActionPerformed(evt);
            }
        });

        lbl_adresse.setText("Adresse :");

        editor.setViewportView(jEditorPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(editor)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lbl_adresse)
                        .addGap(18, 18, 18)
                        .addComponent(txt_adresse, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_port)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_port, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_valider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_adresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_adresse)
                    .addComponent(txt_port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_port)
                    .addComponent(btn_valider, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editor, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void txt_portActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_portActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_txt_portActionPerformed

	private void txt_adresseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_adresseActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_txt_adresseActionPerformed

	private void btn_validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_validerActionPerformed
		try {
			_contr.add(this.txt_adresse.getText(), Integer.parseInt(this.txt_port.getText()), this);
		}
		catch (IOException ex) {
			ex.printStackTrace();
		}
	}//GEN-LAST:event_btn_validerActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area_content;
    private javax.swing.JButton btn_valider;
    private javax.swing.JScrollPane editor;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_adresse;
    private javax.swing.JLabel lbl_port;
    private javax.swing.JTextField txt_adresse;
    private javax.swing.JTextField txt_port;
    // End of variables declaration//GEN-END:variables

	@Override
	public void update(Observable o, Object arg) {
		if(arg instanceof String){
			String text = (String) arg;
			this.write(text.substring(text.indexOf("\n\n")));
		}
	}
	
    @Override
    public void windowClosing(WindowEvent e) {
		try {
			this._contr.close();
		}
		catch (IOException ex) {
			ex.printStackTrace();
		}
    }

	@Override
	public void windowOpened(WindowEvent e) {
		throw new UnsupportedOperationException("Not supported yet.");
	}

	@Override
	public void windowClosed(WindowEvent e) {
		throw new UnsupportedOperationException("Not supported yet.");
	}

	@Override
	public void windowIconified(WindowEvent e) {
		throw new UnsupportedOperationException("Not supported yet.");
	}

	@Override
	public void windowDeiconified(WindowEvent e) {
		throw new UnsupportedOperationException("Not supported yet.");
	}

	@Override
	public void windowActivated(WindowEvent e) {
		throw new UnsupportedOperationException("Not supported yet.");
	}

	@Override
	public void windowDeactivated(WindowEvent e) {
		throw new UnsupportedOperationException("Not supported yet.");
	}
}
